Laba10/BIPIT_10/Models/Exhibits.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibits()
        {
            this.Moving = new HashSet<Moving>();
        }
    
        public int id_exhibit { get; set; }
        public string exhibit { get; set; }
        public string author { get; set; }
        public string name { get; set; }
        public string material { get; set; }
        public string year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moving> Moving { get; set; }
    }
}

Laba10/BIPIT_10/Models/Halls.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Halls()
        {
            this.Moving = new HashSet<Moving>();
        }
    
        public int id_hall { get; set; }
        public string hall_name { get; set; }
        public string floor { get; set; }
        public string museum { get; set; }
        public string city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moving> Moving { get; set; }
    }
}

Laba10/BIPIT_10/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BIPIT_10.Models;

namespace BIPIT_10.Controllers
{
    public class CreateController : Controller
    {
        galleryEntities gallery = new galleryEntities();

        public ActionResult Index()
        {
            List<SelectListItem> exhibits = new List<SelectListItem>();
            var exhibitsdb =gallery.Exhibits;
            foreach (var item in exhibitsdb)
            {
                exhibits.Add(new SelectListItem { Text = String.Format("{0} | {1} | {2}", item.exhibit, item.author, item.name), Value = item.id_exhibit.ToString() });
            }
            ViewBag.Exhibits = exhibits;

            List<SelectListItem> halls = new List<SelectListItem>();
            var hallsdb = gallery.Halls;
            foreach (var item in hallsdb)
            {
                halls.Add(new SelectListItem { Text = String.Format("{0} | {1} | {2}", item.hall_name, item.museum, item.city), Value = item.id_hall.ToString() });
            }
            ViewBag.Halls = halls;

            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            var e = Convert.ToInt32(form["exhibits"]);
            var h = Convert.ToInt32(form["halls"]);
            var start = Convert.ToDateTime(form["start"]);
            var end = Convert.ToDateTime(form["end"]);
            Moving moving = new Moving
            {
                exhibit_fk = e,
                halls_fk = h,
                date_start = start,
                date_end = end
            };
            gallery.Moving.Add(moving);
            gallery.SaveChanges();
            return Redirect(Url.Action("Index", "Home"));
        }
        public ActionResult Exhibit()
        {
            ViewBag.Message = "Добавить экспонат";
            return View();
        }
        [HttpPost]
        public ActionResult Exhibit(FormCollection form)
        {
            var exhibit = form["exhibit"];
            var author = form["author"];
            var name = form["name"];
            var material = form["material"];
            var year = form["year"];

            Exhibits exhibits = new Exhibits
            {
                exhibit = exhibit,
                author = author,
                name= name,
                material = material,
                year = year
            };
            gallery.Exhibits.Add(exhibits);
            gallery.SaveChanges();
            ViewBag.Message = "Экспонаты";

            return Redirect(Url.Action("Exhibit", "Home"));
        }

        public ActionResult Hall()
        {
            ViewBag.Message = "Залы";

            return View();
        }
        [HttpPost]
        public ActionResult Hall(FormCollection form)
        {
            var h_n = form["hall_name"];
            var f = form["floor"];
            var m = form["museum"];
            var c = form["city"];

            Halls halls = new Halls
            {
                hall_name = h_n,
                floor = f,
                museum = m,
                city = c
            };
            gallery.Halls.Add(halls);
            gallery.SaveChanges();
            ViewBag.Message = "Залы";

            return Redirect(Url.Action("Hall", "Home"));
        }



    }
}

Laba10/BIPIT_10/Controllers/DeleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BIPIT_10.Models;

namespace BIPIT_10.Controllers
{
    public class DeleteController : Controller
    {
        galleryEntities gallery = new galleryEntities();

        public ActionResult Index(int id)
        {
            Moving Moving = new Moving { id = id };

            gallery.Moving.Attach(Moving);
            gallery.Moving.Remove(Moving);
            gallery.SaveChanges();
            return Redirect(Url.Action("Index", "Home"));
        }

        public ActionResult Exhibit(int id)
        {
            ViewBag.Message = "Экспонаты";
            Exhibits exhibits = new Exhibits { id_exhibit = id };

            gallery.Exhibits.Attach(exhibits);
            gallery.Exhibits.Remove(exhibits);
            gallery.SaveChanges();
            return Redirect(Url.Action("Exhibit", "Home"));
        }

        public ActionResult Hall(int id)
        {
            ViewBag.Message = "Залы";
            Halls halls = new Halls { id_hall = id };

            gallery.Halls.Attach(halls);
            gallery.Halls.Remove(halls);
            gallery.SaveChanges();
            return Redirect(Url.Action("Hall", "Home"));
        }
    }
}

Laba10/BIPIT_10/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BIPIT_10.Models;

namespace BIPIT_10.Controllers
{
    public class EditController : Controller
    {
        galleryEntities gallery = new galleryEntities();

        public ActionResult Index(int id)
        {
            ViewBag.Id = id;
            var moving = gallery.Moving.Where(x => x.id == id).FirstOrDefault();
            List<SelectListItem> exhibits = new List<SelectListItem>();
            var exhibitsdb = gallery.Exhibits;
            foreach (var item in exhibitsdb)
            {
                exhibits.Add(new SelectListItem { Text = String.Format("{0} | {1} | {2}", item.exhibit, item.author, item.name), Value = item.id_exhibit.ToString() });
            }
            ViewBag.Exhibits = exhibits;
            ViewBag.Exhibit = gallery.Exhibits.Where(x => x.id_exhibit == moving.exhibit_fk).FirstOrDefault().name;
            List<SelectListItem> halls = new List<SelectListItem>();
            var hallsdb = gallery.Halls;
            foreach (var item in hallsdb)
            {
                halls.Add(new SelectListItem { Text = String.Format("{0} | {1} | {2}", item.hall_name, item.museum, item.city), Value = item.id_hall.ToString() });
            }
            ViewBag.Halls = halls;
            ViewBag.Hall = gallery.Halls.Where(x => x.id_hall == moving.halls_fk).FirstOrDefault().museum;

            ViewBag.start = moving.date_start;
            ViewBag.end = moving.date_end;
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            var e = Convert.ToInt32(form["exhibits"]);
            var h = Convert.ToInt32(form["halls"]);
            var start = Convert.ToDateTime(form["start"]);
            var end = Convert.ToDateTime(form["end"]);
            var id = Convert.ToInt32(form["id"]);

            var moving = gallery.Moving.Where(x => x.id == id).FirstOrDefault();
            moving.halls_fk = h;
            moving.exhibit_fk = e;
            moving.date_start = Convert.ToDateTime(start);
            moving.date_end = Convert.ToDateTime(end);
            gallery.SaveChanges();

            return Redirect(Url.Action("Index", "Home"));
        }
        public ActionResult Exhibit(int id)
        {
            ViewBag.Message = "Экспонаты";
            var exhibit = gallery.Exhibits.Where(x => x.id_exhibit == id).FirstOrDefault();
            ViewBag.exhibit = exhibit.exhibit;
            ViewBag.author = exhibit.author;
            ViewBag.material = exhibit.material;
            ViewBag.name = exhibit.name;
            ViewBag.year = exhibit.year;
            ViewBag.Id = id;
            return View();
        }
        [HttpPost]
        public ActionResult Exhibit(FormCollection form)
        {
            ViewBag.Message = "Экспонаты";
            var id = Convert.ToInt32(form["id"]);
            var exhibit = form["exhibit"];
            var author = form["author"];
            var name = form["name"];
            var material = form["material"];
            var year = form["year"];

            var e = gallery.Exhibits.Where(x => x.id_exhibit == id).FirstOrDefault();
            e.exhibit = exhibit;
            e.author = author;
            e.name = name;
            e.material = material;
            e.year = year;
            gallery.SaveChanges();

            return Redirect(Url.Action("Exhibit", "Home"));
        }

        public ActionResult Hall(int id)
        {
            ViewBag.Message = "Залы";
            var hall = gallery.Halls.Where(x => x.id_hall == id).FirstOrDefault();
            ViewBag.Id = id;
            ViewBag.hall_name = hall.hall_name;
            ViewBag.floor = hall.floor;
            ViewBag.museum = hall.museum;
            ViewBag.city = hall.city;

            return View();
        }
        [HttpPost]
        public ActionResult Hall(FormCollection form)
        {
            var h_n = form["hall_name"];
            var f = form["floor"];
            var m = form["museum"];
            var c = form["city"];
            var id = Convert.ToInt32(form["id"]);
            var hall = gallery.Halls.Where(x => x.id_hall == id).FirstOrDefault();
            hall.hall_name = h_n;
            hall.floor = f;
            hall.museum = m;
            hall.city = c;
            gallery.SaveChanges();
            return Redirect(Url.Action("Hall", "Home"));
        }
    }
}

Laba10/BIPIT_10/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BIPIT_10.Models;

namespace BIPIT_9.Controllers
{
    public class HomeController : Controller
    {
        galleryEntities gallery = new galleryEntities();
        public ActionResult Index()
        {
            return View(gallery.Moving.ToList());
        }

        public ActionResult Exhibit()
        {
            ViewBag.Message = "Экспонаты";
            
            return View(gallery.Exhibits.ToList());
        }

        public ActionResult Hall()
        {
            ViewBag.Message = "Залы";

            return View(gallery.Halls.ToList());
        }
    }
}

Laba10/BIPIT_10/Views/Home/Exhibit.cshtml
@model IEnumerable<BIPIT_10.Models.Exhibits>

<h3>@ViewBag.Message</h3>
@if (User.Identity.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Добавить новый экспонат", "Exhibit", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>ID</th>
        <th>Экспонат</th>
        <th>Автор</th>
        <th>Материал</th>
        <th>Год</th>
        @if (User.Identity.IsAuthenticated)
        {
            <th>Редактировать/Удалить</th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id_exhibit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.exhibit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.material)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.year)
            </td>
            @if (User.Identity.IsAuthenticated)
            {
                <td>
                    @Html.ActionLink("Редактировать", "Exhibit", "Edit", new { id = item.id_exhibit }, null) /
                    @Html.ActionLink("Удалить", "Exhibit", "Delete", new { id = item.id_exhibit }, null)
                </td>
            }
        </tr>
    }
</table>

Laba10/BIPIT_10/Views/Home/Hall.cshtml
@model IEnumerable<BIPIT_10.Models.Halls>

<h3>@ViewBag.Message</h3>
@if (User.Identity.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Добавить новый зал", "Hall", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>ID</th>
        <th>Название зала</th>
        <th>Этаж</th>
        <th>Музей</th>
        <th>Город</th>
        @if (User.Identity.IsAuthenticated)
        {
            <th>Редактировать/Удалить</th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id_hall)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hall_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.floor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.museum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.city)
            </td>
            @if (User.Identity.IsAuthenticated)
            {
                <td>
                    @Html.ActionLink("Редактировать", "Hall", "Edit", new { id = item.id_hall }, null)/
                    @Html.ActionLink("Удалить", "Hall", "Delete", new { id = item.id_hall }, null)
                </td>
            }
        </tr>
    }
</table>

Laba10/BIPIT_10/Views/Home/Index.cshtml
@model IEnumerable<BIPIT_10.Models.Moving>
@{
    ViewBag.Title = "Главная страница";
}

<div class="jumbotron">
    <h1>Лабораторная 10: Лаб 9 + авторизация</h1>
</div>

<div class="row ">

    <h3>@ViewBag.Message</h3>
    @if (User.Identity.IsAuthenticated)
    {
        <p>
            @Html.ActionLink("Добавить новую запись", "Index", "Create")
        </p>
    }
    <table class="table">
        <tr>
            <th>ID</th>
            <th>ID Экспоната</th>
            <th>Экспонат</th>
            <th>Название</th>
            <th>Автор</th>
            <th>ID Зала</th>
            <th>Название Зала</th>
            <th>Музей</th>
            <th>Город</th>
            <th>Дата поступления</th>
            <th>Дата отъезда</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th>Редактировать/Удалить</th>
            }
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.exhibit_fk)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Exhibits.exhibit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Exhibits.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Exhibits.author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.halls_fk)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Halls.hall_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Halls.museum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Halls.city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date_start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date_end)
                </td>

              
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        @Html.ActionLink("Редактировать", "Index", "Edit", new { id = item.id}, null)/
                        @Html.ActionLink("Удалить", "Index", "Delete", new { id = item.id }, null)
                    </td>
                }
            </tr>
        }
    </table>


</div>